name: Build, Deploy and Run
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy app
        uses: appleboy/ssh-action@v1.0.0
        env:
          MONGO_DB_CS: ${{secrets.MONGO_DB_CS}}
          HOST: ${{secrets.SSH_HOST}}
          CUSTOM_SIGNUP_FIELDS_ACTION_SECRETS_JWT_SIGNING_KEY_VALUE: ${{ secrets.CUSTOM_SIGNUP_FIELDS_ACTION_SECRETS_JWT_SIGNING_KEY_VALUE }}
          AUTH0_M2M_CLIENT_ID: 6EzSpmd0yTMbdOLeDnQZb7hufZ3VBWQV
          AUTH0_M2M_CLIENT_SECRET: ${{ secrets.AUTH0_M2M_CLIENT_SECRET }}
        with:
          host: ${{secrets.SSH_HOST}} # IP address of the server you wish to ssh into
          username: ${{ secrets.SSH_USERNAME }} # User of the server you want to ssh into
          password: ${{ secrets.SSH_PASSWORD }}
          envs: MONGO_DB_CS,HOST,CUSTOM_SIGNUP_FIELDS_ACTION_SECRETS_JWT_SIGNING_KEY_VALUE,AUTH0_M2M_CLIENT_SECRET,AUTH0_M2M_CLIENT_ID
          script: |
            cd repos/media-scrapper-server
            git pull
            echo 'Grabbed files from repo'
            cd .droplet-scripts
            bash media-scrapper-server-pid-file-handler.sh
            chmod +x add-or-update-env-variable.sh
            bash add-or-update-env-variable.sh CUSTOM_SIGNUP_FIELDS_ACTION_SECRETS_JWT_SIGNING_KEY_VALUE $CUSTOM_SIGNUP_FIELDS_ACTION_SECRETS_JWT_SIGNING_KEY_VALUE
            chmod +x add-or-update-env-variable.sh
            bash add-or-update-env-variable.sh M2M_CLIENT_SECRET $AUTH0_M2M_CLIENT_SECRET
            cd ../MediaScrapperAPI
            jq --arg mongoDbCs "$MONGO_DB_CS" --arg auth0ClientId "$AUTH0_M2M_CLIENT_ID" '.MongoDbSettings.ConnectionString |= $mongoDbCs | .Auth0M2MSettings.ClientId |= $auth0ClientId' appsettings.json > appsettings.json.tmp
            mv appsettings.json.tmp appsettings.json
            echo 'Altered config file with secrets'
            dotnet build --configuration Release
            echo 'App built'
            cd bin/Release/net8.0/
            nohup ./MediaScrapper --urls https://$HOST/ > /dev/null 2>&1 & echo $! > /root/repos/media-scrapper-server/.droplet-scripts/media-scrapper-server-pid-file.txt
            echo 'Deployment successful to digital ocean' 
