name: Build, Deploy and Run
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy app
        uses: appleboy/ssh-action@v1.0.0
        env:
          MONGO_DB_CS: ${{secrets.MONGO_DB_CS}}
          HOST: ${{secrets.SSH_HOST}}
        with:
          host: ${{secrets.SSH_HOST}} # IP address of the server you wish to ssh into
          username: ${{ secrets.SSH_USERNAME }} # User of the server you want to ssh into
          password: ${{ secrets.SSH_PASSWORD }}
          envs: MONGO_DB_CS,HOST
          script: |
            cd repos/media-scrapper-server
            git pull
            cd MediaScrapperAPI
            jq --arg newValue "$MONGO_DB_CS" '(.MongoDbSettings.ConnectionString) |= $newValue' appsettings.json
            dotnet build --configuration Release
            nohup dotnet run --urls https://$HOST > /dev/null 2>&1 &
            echo 'Deployment successful to digital ocean' 
            exit
