name: Build, Deploy and Run
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy app
        uses: appleboy/ssh-action@v1.0.0
        env:
          MONGO_DB_CS: ${{secrets.MONGO_DB_CS}}
          HOST: ${{secrets.SSH_HOST}}
        with:
          host: ${{secrets.SSH_HOST}} # IP address of the server you wish to ssh into
          username: ${{ secrets.SSH_USERNAME }} # User of the server you want to ssh into
          password: ${{ secrets.SSH_PASSWORD }}
          envs: MONGO_DB_CS,HOST
          script: |
            cd repos/media-scrapper-server
            git pull
            echo 'Grabbed files from repo'
            cd .droplet-scripts
            bash media-scrapper-server-pid-file-handler.sh
            cd ../MediaScrapperAPI
            jq --arg newValue "$MONGO_DB_CS" '(.MongoDbSettings.ConnectionString) |= $newValue' appsettings.json > /dev/null
            echo 'Altered config file with secrets'
            dotnet build --configuration Release
            echo 'App built'
            cd bin/Release/net7.0/
            nohup MediaScrapper --urls https://$HOST/ > /dev/null 2>&1 & echo $! > /root/repos/media-scrapper-server/.droplet-scripts/media-scrapper-server-pid-file.txt
            echo 'Deployment successful to digital ocean' 
